### ISSUE TITLE
Style / CSS eliminates collapsibility

### ISSUE THREAD

**Issue by code-SL** [aquirdTurtle/Collapsible_Headings#6]
Respects html tags (`<h1>`, `<h2>`, etc) but when inserting style / css element such as
```html
<h1 style="color : red">content</h1>
```

the collapsibility disappears.  

Would be great to preserve collapsibility with in-line css elements somehow?

**Comment by aquirdTurtle** [comment]
Thanks for pointing this out. This should be fixed in the recently released version 0.4.2. I changed the regex catching these headers to `/<h([1-6])(.*)>(.*)<\/h\1>/i` which should catch anything like this. I'm not very familiar with the different css options for things like this, so let me know if there are any further problems.
